site_name: Telco Integrator
site_url: https://github.com/IBM/telco-integrator/
site_description: describe asset
theme: 
  name: material
features:
  - navigation.instant
  - navigation.tabs
  - navigation.expand
nav:
- Overview: index.md
- Business Case: biz_case.md
- Integrator Solution Overview: solution_overview.md
- Hybrid Reference Architecture: hybrid_ref-arch.md
- IBM CP4I Capabilites: cp4i-capabilities.md
- TMF Open APIs Integrated: tmf-apis_in_cp4i.md
- Market Your APIs: devportal.md
- API Connect Analytics: analytics.md
- Infuse Artificial Intelligence: cp4d-ai.md
