site_name: Accelerator for Telco
site_url: https://github.com/IBM/telco-integrator/
site_description: Asset for telco CSPs
# Copyright
copyright: <a href="/about/">IBM</a>
docs_dir: staging
theme: 
    name: material
#    custom_dir: custom_theme
#    logo: banner.png
#    favicon: 'aot.png'
    show_sidebar: true
    palette:
        primary: 'black'
        accent: 'red'
    font:
        text: 'IBM Plex Sans'
        code: 'IBM Plex Mono'
    features:
        - navigation.instant
#        - navigation.tabs
        - navigation.sections
nav:
- Home: 'index.md'
- Business Case: 'biz_case.md'
- Reference Architecture: 'hybrid_ref-arch.md'
- Integrator Solution Overview: 'solution_overview.md'
- IBM CP4I Capabilites: 'cp4i-capabilities.md'
- TMF Open APIs Integrated: 'tmf-apis_in_cp4i.md'
- Monetize Your APIs: 'devportal.md'
- API Connect Analytics: 'analytics.md'
- Infuse Artificial Intelligence: 'cp4d-ai.md'

# Markdown extensions
markdown_extensions:
    - admonition
    - toc:
        baselevel: 4
        separator: "-"
        permalink: True
    - sane_lists

# Plugins
plugins:
    - search:
        separator: '[\s\-\.]+'
        prebuild_index: true
#    - macros
  
extra_javascript:
    - js/extra.js 
